### ISSUE TITLE
Gyógyszerelés követése

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#12]
Felhasználóként szeretném, hogy a rendszer rögzítse az általam felírt gyógyszereket és azok adagolását, hogy a jövőbeni látogatások alkalmával könnyen hozzáférjek ezekhez az információkhoz.

**Comment by rizzilla** [comment]
Navigációs sávon "Gyógyszerezések áttekintése" fülre kattintva megjelenik a gyógyszerezések áttekintése oldal.

A keresési sáv melletti hozzáadás gombra kattintás után megjelenik a gyógyszerezés űrlap.
Az oldal bal oldalán található a navigációs sáv. Tőle jobbra láthatóak a beviteli mezők egymás alatt elhelyezkedve. Látható a mező megnevezése és a mező. Az oldal legalján található egy "Hozzáadás", ami feltölti a rendszerbe az új adatot. Feltöltés után megjelenik egy felugró ablak, hogy sikeres volt-e az adat rögzítése. Annak az ablak alján található egy "Ok" gomb, ami lenyomása után átugrik a rendszer az állat adatlapjára.

### Követelmények:

- Egy űrlap ami lehetőséget biztosít az alábbi adatok felvételére:
- Gazda személyi száma (keresési mezővel egy listából)
- Gazda állatának neve (listából)
- Gyógyszer (listából)
- Napi mennyiség
- Megjegyzés
