### ISSUE TITLE
Időpontfoglalás kezelése

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#19]
Mint állatorvosi asszisztens, szeretném hatékonyan szervezni az időpontokat és a páciensek fogadását, hogy a rendelés gördülékenyen menjen.

**Comment by rizzilla** [comment]
Navigációs sávon Időpontok áttekintése fülre kattintva megjelenik a időpontok áttekintése oldal. Bal felső sarokban látszódik egy kör, amire kattintva megjelenik és eltűnik. A képernyő két részre van osztva vízszintesen, felül gombok találhatók alul egy felül változtatható naptár. A felső rész közepén két gombbal be lehet állítani a naptár heti vagy havi lebontása között. Jobboldalt még két gomb található, "új időpont hozzáadása" és "ugrás a mai napra".  A naptár részlegen heti felbontásban látszódik a hónap neve és a héthez vonatkozó dátumok. Ezek baloldalt 0-24 óráig időbeosztás óránként található. A dátumok alatt látszódnak időpontok beosztása alapján az időpontok egy jól látható alakzatban. Rákattintva látható a gazda neve, állat neve, időpont óra perc kimutatása és korábbi megjegyzés Alul gomb található, amivel törölni lehet a bejegyzést. Időpontot manuális áthúzással lehet más időpontra rakni. 
Az időpont hozzáadás gombra kattintva egy átfedő ablak jelenik meg, amin a megfelelő megnevezések és beviteli mezők vannak. Alul a "Hozzáadás" gombbal lehet bejegyezni az időpontot. Rögzítés után megjelenik egy felugró ablak, hogy sikeres volt-e az adat rögzítése. Annak az ablak alján található egy "Ok" gomb, ami lenyomása után a bejegyzett dátum napjához ugrik és egy kis ablakban változtathatóak az adatok.

### Követelmények időpont rögzítéséhez:

- Egy űrlap ami lehetőséget biztosít az alábbi adatok felvételére:
- Gazda neve (keresőmező és lista)
- Állat neve (keresőmező és lista)
- Naptár szabad időpontok jelölésével
- Megjegyzés

### Követelmények az áttekintés oldalhoz:

- Heti és havi áttekintés gomb
- Új időpont rögzítése gomb
- Ugrás a mai napra gomb
- Kattintható időpont
- Áthúzható időpont

### If/Then Behaviors időpont rögzítéséhez

- Ha bármelyik mező üresen marad, Akkor nem engedi az adat rögzítését és a mező alatt kiírja a hibát.
- Ha a gazda neve nem csak betűt tartalmaz,  Akkor nem engedi az adat rögzítését és a mező alatt kiírja a hibát.
- Ha az állat neve nem csak betűt tartalmaz,  Akkor nem engedi az adat rögzítését és a mező alatt kiírja a hibát.
- Ha naptárban már foglalt egy időpont, ne lehessen kiválasztani.
- Ha a fentiek alapján sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
Ha szerver miatt sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".

### If/Then Behaviors áttekintés oldalhoz:

- Ha az időpont már egy foglalt időponthoz kerül áthúzásra, Akkor dobja vissza a kiinduló mezőjébe.
