### ISSUE TITLE
Gyógyszerezési ütemezés

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#20]
Mint állatorvosi asszisztens és felhasználó, szeretném hogy beállíthassam, és nyomonkövethessem a megfigyelésre bent tartott állatok gyógyszerezési ütemezését.

**Comment by rizzilla** [comment]
Navigációs sávon "Benntartott állatok" fülre kattintva megjelenik a gyógyszerezések áttekintése oldal.
Baloldalt látható a navigációs sáv, jobbra tőle egy keresési mező, alatta pedig a benntartott állatok elnyújtott dobozokban. Balról jobbra ezekben található az állat neve, gazdájáról információ, faja, fajtája, utolsó gyógyszerelési időpont, Rákattintva előhoz egy átfedő lapot, amin a pontos adatok látszódnak az állatról fentről-lefelé: állat neve, gazdája, benntartás kezdeti időpontja, gyógyszerek és napi adagjuk, megjegyzés. Alul kettő gomb található balról jobbra: "Mentés","Mégse".

### Követelmények

- Gazda neve (nem változtatható)
- Állat neve (nem változtatható)
