### ISSUE TITLE
Ügyfelek elérhetősége

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#21]
Mint állatorvosi assisztens, szerentém elérni az ügyfeleink email és telefonszám elérhetőségét a gördülékeny kommunikáció érdekében.

**Comment by rizzilla** [comment]
Navigációs sávon a tulajdonosok áttekintése fülre kattintva megjelenik a tulajdonosok áttekintése oldal. Baloldalt látszódik a navigációs sáv, a képernyő többi részén a keresési sáv felül, alatta pedig egy görgethető lista a tulajdonosok adataival. A listában valamelyik elemre kattintva feldob egy átfedő lapot, amelyen megjelennek a kiválasztott tulajdonosnak az adatai fentről lefelé. Ezek alatt található egy megjegyzés mező és 2 gomb. Baloldalt egy "Módosítás" jobboldalt egy "Mégse" gomb. A "Módosítás" gombra nyomva tudjuk változtatni a tulajdonos adatait. Ilyenkor alul megjelenik egy "Mentés" gomb a "Mégse" mellett. Mentés gomb lenyomása után megkérdezi felugró ablakban, hogy biztosan módosítjuk az adatokat, ha nem dobjon vissza a módosítatlan adatokhoz. Sikeres mentés esetén pedig megjelenik egy felugró ablak, amin látható, hogy sikeres volt-e a mentés. Ennek az alján található egy "Ok" gomb amivel be lehet zárni és visszadob a kiválasztott tulajdonos lapjához.

### Követelmények

- Egy űrlap, ami biztosítja a következő adatok változtatását:
- Név
- Telefonszám (elől a nemzetnek kezdő számai listában)
- Ímél
- Irányítószám
- Lakcím
- Emelet (opcionális)
- Ajtószám (opcionális)
- Személyigazolvány száma?
- Módosítás gomb
- Mégse gomb
- Mentés gomb

### If/Then Behaviors

- Ha a "Módosítás" gombra nyomunk, Akkor lehessen a beírt adatokat módosítani.
- Ha nem módosítunk semmilyen adatot, Akkor figyelmeztetés nélkül lehessen kilépni a módosításból.
- Ha a "Módosítás" gombot megnyomjuk, Akkor váljon kattinthatóvá a "Mentés" gomb.
- Ha  módosítás közben üresen hagyunk mezőt, kivéve az emelet és ajtószám opciókat, Akkor nem engedi az adat módosítását és a mező alatt kiírja a hibát.
- Ha nem módosítjuk az adatokat, Akkor dobjon vissza az kezdeti személyi adatokhoz.
- Ha a név nem csak betűből áll, Akkor nem engedi az adat módosítását és a mező alatt kiírja a hibát.
- Ha a telefonszám nem kilenc számból áll, Akkor nem engedi az adat módosítását és a mező alatt kiírja a hibát.
- Ha az ímél nem egyezik meg a formai követelményekkel, Akkor nem engedi az adat módosítását és a mező alatt kiírja a hibát.
- Ha az irányítószám nem csak számot tartalmaz, Akkor nem engedi az adat módosítását és a mező alatt kiírja a hibát.
- Ha az emelet nem csak számot tartalmaz, Akkor nem engedi az adat módosítását és a mező alatt kiírja a hibát.
- Ha az ajtószám nem csak számot tartalmaz, Akkor nem engedi az adat módosítását és a mező alatt kiírja a hibát.
- (Ha a személyigazolvány szám nem felel meg a formai követelményeknek, Akkor nem engedi az adat módosítását és a mező alatt kiírja a hibát.)
