### ISSUE TITLE
Profil módosítása

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#28]
Adminisztrátorként szeretném hogy az összes felhasználó profilját önmaga tudja módosítani. 
Szeretném hogy legyen a felhasználóknak profilképe, telefonszáma, emailje.
Az állat gazdák csak a saját adatlapjukat tudják megtekinteni. 
Adminisztrátorként szeretném hogy tudjam modosítani mindenki profilját.

**Comment by rizzilla** [comment]
A rendelő oldala megnyitása után látható egy regisztráció és egy bejelentkezés téglalap. A regisztrációra nyomva található beviteli mezők megfelelő címkékkel egymás alatt. Alul található egy "Mentés" gomb. Sikeres mentés után megjelenik egy felugró ablak, hogy sikeres volt-e a mentés.Annak az ablak alján található egy "Ok" gomb, ami lenyomása után átirányít a főoldalra. Adminisztrátorként változtathatóak a profilok adatai a navigációs menü profilok áttekintése fülében.

### Követelmények:

- Egy űrlap, ami lehetőség biztosít a következő adatok megadására:
- Ímél
- Jelszó
- Profilkép beállítása (méret limitálva)
- Telefonszám (előtagok listából)

### If/Then Behaviors

- Ha az ímélcím már használva van vagy nem felel meg a formai szabványoknak, Akkor nem engedi az adat mentését és a mező alatt kiírja a hibát.
- Ha a két jelszó nem egyezik, Akkor nem engedi az adat mentését és a mező alatt kiírja a hibát.
- Ha a profilkép mérete nagyobb a megengedettnél, Akkor nem engedi az adat mentését és a mező alatt kiírja a hibát.
- Ha a telefonszám nem csak 9 számot tartalmaz, Akkor nem engedi az adat mentését és a mező alatt kiírja a hibát.
