### ISSUE TITLE
Jelszó módosítása

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#29]
Adminisztrátorként szeretném hogy a felhasználók tudjanak jelszó emlékeztetőt kérni amennyiben elfelejtik.
Szeretném, ha a felhasználók módosítani tudják a jelszavukat.
Adminisztrátorként szeretném ha módosítani tudnám mindenki jelszavát.

**Comment by rizzilla** [comment]
A rendelő oldala megnyitása után látható egy regisztráció és egy bejelentkezés téglalap. A bejelentkezésre nyomva látható a bejelentkezéshez szükséges adatok megadási mezői és hozzájuk tartozó címkék. Ezek alatt található egy "Elfelejtettem a jelszavam" lehetőség. Legalul egy "Belépés" és "Vissza" gomb. Az elfelejtettem a jelszavam gombra nyomva felad egy űrlapot, amelyen a profil íméljét kell megadni alatta pedig egy küldés gomb található. A gomb lenyomása után kap a felhasználó egy ímélt, amire nyomva felugrik egy űrlap, amin meg kell adni az új jelszót kétszer. Közben a másik oldal visszairányít a bejelentkezés oldalra. Ha sikeres volt a bejelentkezés, akkor bedobja a felhasználót a főoldalra. Adminisztrátor tudja a jelszavakat változtatni viszont nem látja a korábban beállítottakat. Ezt a navigációs menü profilok áttekintése fülében teheti meg.

### Követelmények:

- Két űrlap, ami lehetőség biztosít a következő adatok megadására:
- Ímél
- Jelszó(k)
- Elfelejtett jelszó gomb
- Bejelentkezés gomb
- Mégse gomb

### If/Then Behavior

- Ha az ímélcím nem létezik az adatbázisban vagy nem felel meg a formai szabványoknak, Akkor nem engedi a felhasználó továbblépését és a mező alatt kiírja a hibát.
- Ha hibás a megadott jelszó, Akkor nem engedi a felhasználó továbblépését és a mező alatt kiírja a hibát.
- Ha a felhasználó nem nyitja meg a megkapott ímélt időben, Akkor nem változtathat bizonyos ideig jelszót.
- Ha a két jelszó nem egyezik meg, Akkor nem engedi az új jelszó mentését és a mező alatt kiírja a hibát.
- Ha a fentiek alapján sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
- Ha szerver miatt sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
