### ISSUE TITLE
Ismeretlen fajok

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#33]
Adminisztrátorként szeretném, hogyha a páciens első felvételekor nem található a faj, akkor a ügyintéző fel tudja vinni az adatbázisba, és az adminisztrátoroknak jelenjen meg ellenőrzésre.

**Comment by rizzilla** [comment]
Navigációs sávon az "Értesítések" fül mellett látható egy ikon és egy szám, amely azt mutatja, hogy hány értesítés érkezett a legutóbbi megtekintés óta. Erre a fülre kattintva megnyílik az értesítések oldal.

Baloldalt található a navigációs sáv, jobbra tőle egy keresési mező, mellette három gomb, amellyel ki lehet választani, hogy az üzenetek, műveletek vagy az összes értesítést mutassa, alatta pedig az értesítések az üzenet tartalmára utaló névvel. Az üzenetre rányomva egy átfedő ablak megjelenik, amelyen szerepel a kérdéses művelet, alatta pedig az adat. Ezek alatt található három gomb, "Hozzáadás", "Változtatás" és "Más faj megadása". Legalul látható egy "Mégse" gomb, amivel vissza lehet lépni az értesítések oldalra. A hozzáadás gomb lenyomása után egy felugró ablak, hogy sikeres volt-e az adat(ok) rögzítése. Annak az ablak alján található egy "Ok" gomb, amire kattintás után átugrik a páciens korábbi kezeléseinek áttekintő lapjára.

### Követelmények

- Szűrő gomb
- Beviteli mező
- Hozzáadás gomb
- Változtatás gomb
- Más faj gomb
- Mégse gomb

### If/Then Behaviors

- Ha a beviteli mező nem csak betűt és kötőjelet tartalmaz Akkor nem engedi az adat rögzítését és a mező alatt kiírja a hibát.
- Ha a "Más faj megadása" gombra nyom a felhasználó, Akkor egy legördülő listából lehessen kiválasztani a fajt.
- Ha a faj nincs kiválasztva a listából, Akkor nem engedi az adat rögzítését és a mező alatt kiírja a hibát.
- Ha a fentiek alapján sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
Ha szerver miatt sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
