### ISSUE TITLE
Saját időpontok kezelése

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#34]
Szeretném ha bejelentkezés után meg tudnám tekinteni a saját időpontjaimat, újat foglalni, áthelyezni, törölni tudnám őket.

**Comment by rizzilla** [comment]
A főoldalon jobb felül található a profilkép. Arra kattintva átvisz a felhasználó adatainak áttekintése oldalra. Baloldalt található a navigációs sáv, tőle jobbra a felhasználó adatai egymás alatt, attól jobbra egy másik navigációs sáv, amelyen a felhasználóhoz rendelt állatok és hozzájuk tartozó adatlapjaik láthatóak, időpontok kezelése, és felhasználói adatok kezelése. 





Kapcsolódó User Storyk: #28, #19
