### ISSUE TITLE
Regisztráció

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#35]
Szeretnék regisztrálni a weblapon keresztül.

**Comment by rizzilla** [comment]
A rendelő oldala megnyitása után látható egy regisztráció és egy bejelentkezés téglalap. A regisztrációra nyomva található beviteli mezők megfelelő címkékkel egymás alatt. Alul található egy "Mentés" gomb. Sikeres mentés után megjelenik egy felugró ablak, hogy sikeres volt-e a mentés.Annak az ablak alján található egy "Ok" gomb, ami lenyomása után átirányít a főoldalra. Adminisztrátorként változtathatóak a profilok adatai a navigációs menü profilok áttekintése fülében.
Követelmények:

    Egy űrlap, ami lehetőség biztosít a következő adatok megadására:
    Ímél
    Jelszó
    Profilkép beállítása (méret limitálva)
    Telefonszám (előtagok listából)

If/Then Behaviors

    Ha az ímélcím már használva van vagy nem felel meg a formai szabványoknak, Akkor nem engedi az adat mentését és a mező alatt kiírja a hibát.
    Ha a két jelszó nem egyezik, Akkor nem engedi az adat mentését és a mező alatt kiírja a hibát.
    Ha a profilkép mérete nagyobb a megengedettnél, Akkor nem engedi az adat mentését és a mező alatt kiírja a hibát.
    Ha a telefonszám nem csak 9 számot tartalmaz, Akkor nem engedi az adat mentését és a mező alatt kiírja a hibát.
    Ha a fentiek alapján sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
    Ha szerver miatt sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
