### ISSUE TITLE
Bejelentkezés

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#36]
Szeretnék bejelentkezni a weboldalon keresztül.

**Comment by rizzilla** [comment]
A rendelő oldala megnyitása után látható egy regisztráció és egy bejelentkezés téglalap. A bejelentkezésre nyomva látható a bejelentkezéshez szükséges adatok megadási mezői és hozzájuk tartozó címkék. Ezek alatt található egy "Elfelejtettem a jelszavam" lehetőség. Legalul egy "Belépés" és "Vissza" gomb. Ha sikeres volt a bejelentkezés, akkor bedobja a felhasználót a főoldalra. Adminisztrátor tudja a jelszavakat változtatni viszont nem látja a korábban beállítottakat.

### Követelmények:

-  Két űrlap, ami lehetőség biztosít a következő adatok megadására:
-  Ímél
-  Jelszó
-  Elfelejtett jelszó gomb
-  Bejelentkezés gomb
-  Mégse gomb

### If/Then Behavior

-     Ha az ímélcím nem létezik az adatbázisban vagy nem felel meg a formai szabványoknak, Akkor nem engedi a felhasználó továbblépését és a mező alatt kiírja a hibát.
-     Ha hibás a megadott jelszó, Akkor nem engedi a felhasználó továbblépését és a mező alatt kiírja a hibát.
-     Ha a fentiek alapján sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
-     Ha szerver miatt sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
