### ISSUE TITLE
Saját állatok adatlapjainak megtekintése

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#37]
Meg szeretném tekinteni az állatim adatlapját.

**Comment by rizzilla** [comment]
A főoldalon jobb felül található a profilkép. Arra kattintva átvisz a felhasználó adatainak áttekintése oldalra. Baloldalt található a navigációs sáv, tőle jobbra a felhasználó adatai egymás alatt, attól jobbra egy másik navigációs sáv, amelyen a felhasználóhoz rendelt állatok és hozzájuk tartozó adatlapjaik láthatóak, időpontok kezelése, és felhasználói adatok kezelése. Az állatok adatlapjainak áttekintése fülre kattintva átviszi a felhasználót az állatok adatlapjainak áttekintése oldalra. Bal- és jobboldalt találhatók a navigációs menük. Középen téglalapokban az állat(ok) nevei. Rákattintva egyre egy felugró ablak jelenik meg, ahol láthatóak az állat pontos adatai.

### Funkcionális követelmények

- Lehetőség az állatok adatainak külön-külön való megtekintésére.


Kapcsolódó User Storyk: #10 #28
