### ISSUE TITLE
Páciensek kezelése

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#39]
Szeretnék egy oldalt ahol kereshetek a páciensek között, és azon keresztül megtekinthetem a páciens adatlapját.

**Comment by rizzilla** [comment]
Navigációs sávon "páciensek áttekintése" fülre kattintva megjelenik a páciensek áttekintése oldal.

A keresési sávba a gazda egyik adatának beírása után a mező alatt felhozza az állatainak találatait egy-egy téglalapban. A téglalapban balról jobbra haladva található az állat neve; faja; utolsó kezelés időpontja. Rákattintva egy átfedőlapon megjelenik felül kilistázva a páciens adatai és oltása(i) dátummal feltüntetve. Alatta találhatóak korábbi vizsgálatai dátummal és problémával. Rájuk kattintva egymás alatt megjelennek a kezelési adatok.

### Követelmények:

- Reszponzivitás
