### ISSUE TITLE
Gyógyszerek felvétele

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#42]
Adminisztrátorként szeretném ha az új gyógyszereket fel tudnám venni az adatbázisba.

**Comment by rizzilla** [comment]
Navigációs sávon gyógyszerkészlet kezelése fülre kattintva megjelenik a  gyógyszerkészlet kezelése oldal. Balra található a navigációs menü, tőle jobbra egy keresési mező, alatta pedig a gyógyszerek és azok adatai egy-egy dobozban. Jobb felső sarokban található egy "új gyógyszer" hozzáadása gomb mellette egy fogaskerék ikon (beállítások). Az új gyógyszer ikonjára kattintás után felugrik egy átfedő lap, amelyen találhatóak a bevitelhez való mezők és hozzájuk tartozó címkék egymás alatt. Az oldal legalján található egy "Feltöltés" és egy "Mégse gomb", ami feltölti a rendszerbe az új adatot. Feltöltés után megjelenik egy felugró ablak, hogy sikeres volt-e az adat rögzítése. Annak az ablak alján található egy "Ok" gomb, ami lenyomása után átugrik a rendszer az állat adatlapjára. 

### Követelmények:

- Egy űrlap ami lehetőséget biztosít az alábbi adatok felvételére:
- Gyógyszer neve
- Gyógyszer mértékegysége (mg, ml, tabletta. stb listából)
- Figyelmeztetés adott darabszám alatt (egyéni érték felülírja a kollektívet)
- Mentés gomb
- Mégse gomb

### If/Then Behaviors

- Ha bármelyik mező üresen marad, Akkor nem engedi az adat rögzítését és a mező alatt kiírja a hibát.
- Ha a gyógyszer neve létezik már, Akkor nem engedi az adat rögzítését és a mező alatt kiírja a hibát.
- Ha a gyógyszer mértékegysége nincs kiválasztva, Akkor nem engedi az adat rögzítését és a mező alatt kiírja a hibát.
- Ha a figyelmeztetés nem csak számot tartalmaz, Akkor nem engedi az adat rögzítését és a mező alatt kiírja a hibát.
- Ha a fentiek alapján sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
Ha szerver miatt sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
