### ISSUE TITLE
Gógyszer készlet regisztrálása

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#43]
Szeretném ha módosítani tudnám a gyógyszer készlet mennyiségét.

**Comment by rizzilla** [comment]
Navigációs sávon gyógyszerkészlet kezelése fülre kattintva megjelenik a gyógyszerkészlet kezelése oldal. Balra található a navigációs menü, tőle jobbra egy keresési mező, alatta pedig a gyógyszerek és azok adatai egy-egy dobozban.Jobb felső sarokban található egy "új gyógyszer" hozzáadása gomb mellette egy fogaskerék ikon (beállítások). Egy gyógyszer dobozára a kurzort rávéve megjelenik egy kis ikon, amire rányomva felugrik egy átfedő lap. Ezen a lapon látható beviteli mezők és hozzájuk tartozó címkék egymás alatt. Alul található két gomb: "Mentés", "Mégse". Sikeres mentés után megjelenik egy felugró ablak, hogy sikeres volt-e a mentés.Annak az ablak alján található egy "Ok" gomb, ami lenyomása után kilép a beállításokból.

### Követelmények:

- Egy űrlap, ami lehetőséget biztosít a következő adatok módosítására:
- Gyógyszer neve módosítása
- Gyógyszer mennyisége (db)
- Megjegyzés
- Mentés gomb
- Mégse gomb

### If/Then Behaviors

- Ha a gyógyszer neve már létezik, Akkor nem engedi az adat mentését és a mező alatt kiírja a hibát.
- Ha gyógyszer mennyisége nem csak számot tartalmaz, Akkor nem engedi az adat mentését és a mező alatt kiírja a hibát.
- Ha a megjegyzés üresen marad, Akkor nem engedi az adat mentését és a mező alatt kiírja a hibát.
- Ha a fentiek alapján sikertelen a mentés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
Ha szerver miatt sikertelen a mentés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
