### ISSUE TITLE
Megfigyelés alatt álló állatok kezelése

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#44]
Szeretném hogy legyen egy oldal, ahol át tudom tekinteni a megfigyelés alatt álló állatokat, és azon keresztül is kezelni őket.

**Comment by rizzilla** [comment]
Navigációs sávon "Megfigyelt állatok kezelése" fülre kattintva megjelenik a Megfigyelt állatok kezelése oldal.
Baloldalt látható a navigációs sáv, jobbra tőle egy keresési mező, alatta pedig a benntartott állatok elnyújtott dobozokban. Balról jobbra ezekben található az állat neve, gazdájáról információ, faja, fajtája, utolsó gyógyszerelési időpont, Rákattintva előhoz egy átfedő lapot, amin a pontos adatok látszódnak az állatról fentről-lefelé: állat neve, gazdája, benntartás kezdeti időpontja, gyógyszerek és napi adagjuk, megjegyzés, hazaküldhető-e és mikor volt utoljára szerkeztve. Alul három gomb található balról jobbra: "Mentés", "Szerkesztés", "Mégse". A keresési mező mellett látható egy "Táblázat nézet" gomb. Sikeres mentés után megjelenik egy felugró ablak, hogy sikeres volt-e az adat rögzítése. Annak az ablak alján található egy "Ok" gomb, ami lenyomása után a bejegyzett dátum napjához ugrik és egy kis ablakban változtathatóak az adatok.

### Követelmények:

- Átfedő lap, ami lehetőséget biztosít a következő adatok megtekintésére, és szerkesztésére:
- Gazda neve (nem változtatható)
- Állat neve (nem változtatható)
- Faj (nem változtatható)
- Fajta (nem változtatható)
- Utolsó gyógyszerelés időpontja (nem változtatható)
- Gyógyszer(ek)
- Napi mennyiség
- Megjegyzés
- Hazaküldhető (igen-nem)
- Mentés gomb
- Változtatás gomb
- Mégse gomb

### If/Then Behaviors

- Ha a változtatás gombra nyom a felhasználó, Akkor legyen új gyógyszer hozzáadható egy új napi mennyiség beállításával és el is lehessen venni már meglévőt.
- Ha a gyógyszer mező üresen marad, Akkor ugorjon fel egy ablak "Hiba" felirattal és dobjon vissza az előző lapra.
- Ha a napi mennyiség mezők közül üresen marad bármelyik, Akkor ugorjon fel egy ablak "Hiba" felirattal és dobjon vissza az előző lapra.
- Ha hazaküldhető az állat, Akkor a mentés után küldjön ki a gazdának egy értesítőt, amellyel megtudja, hogy hazavihető az állata.
- Ha a mentés sikertelen, Akkor ugorjon fel egy ablak "Hiba" felirattal és dobjon vissza az előző lapra.
- Ha a mégse gombra kattintunk, Akkor dobjon vissza minket az áttekintés oldalra.
