### ISSUE TITLE
Állat felvétele megfigyelés alá

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/Vizsgaremek#45]
Szeretném ha be tudnám állatani, hogy az állat megfigyelés alatt áll.
Szeretném, ha el tudnám tárolni hogy miért van bent megfigyelésen, meddig van bent megfigyelésen, és melyik tárolóban található az állat.

**Comment by rizzilla** [comment]
Navigációs sávon "páciensek áttekintése" fülre kattintva megjelenik a páciensek áttekintése oldal.

A keresési sávba a gazda egyik adatának beírása után a mező alatt felhozza az állatainak találatait egy-egy téglalapban. A téglalapban balról jobbra haladva található az állat neve; faja; utolsó kezelés időpontja. Rákattintva egy átfedőlapon megjelenik felül kilistázva a páciens adatai és oltása(i) dátummal feltüntetve. Alatta találhatóak korábbi vizsgálatai dátummal és problémával. Rájuk kattintva egymás alatt megjelennek a kezelési adatok. Legalul található egy "Benntartás" gomb.

A benntartás gombra kattintva az átfedőlap megváltozik a benntartáshoz szükséges adatok megadásához. Alul vissza lépni az előző lapra és menteni lehet az adatokat. Feltöltés után megjelenik egy felugró ablak, hogy sikeres volt-e az adat rögzítése. Annak az ablak alján található egy "Ok" gomb, ami lenyomása után átugrik a rendszer a benntartott állatok lapjára, ahol megnyitja a hozzáadott állat adatlapját.

### Követelmények:

- Egy űrlap ami lehetőséget biztosít az alábbi adatok felvételére:
- Benntartás oka
- Kiengedés időpontja
- Tároló kiválasztása (méret szerint listából)
- Mentés gomb
- Vissza gomb

### Funkcionális követelmények:

- Lehetőség dátum megadására naptárból
- Kiválasztott tároló méret alapján egy tároló hozzárendelése
- QR kód azonosító létrehozása a rendszer által
- Lehetőség az adatok áttekintésére és szerkesztésére

### If/Then Behaviors

- Ha az ok mező üres vagy speciális karaktereket tartalmaz (kivéve -), Akkor nem engedi az adat rögzítését és a mező alatt kiírja a hibát.
- Ha nincs szabad tároló, Akkor nem engedi az adat rögzítését és a mező alatt kiírja a hibát.
- Ha nincs kiválasztva a tároló mérete, Akkor nem engedi az adat rögzítését és a mező alatt kiírja a hibát.
- Ha a fentiek alapján sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".
Ha szerver miatt sikertelen a feltöltés, Akkor feldob egy ablakot és kiírja, hogy "Hiba".


Kapcsolódó User Story(k): #39
